### ISSUE TITLE
contact | liuzhihang

### ISSUE THREAD

**Issue by liuzhihangs** [liuzhihangs/liuzhihang.github.io#127]
https://liuzhihang.com/contact/ 

 contact | liuzhihang

**Comment by JTXYH** [comment]
博客做的真好看！

**Comment by liuzhihangs** [comment]
> @JTXYH
> 博客做的真好看！

感谢肯定,  这块用的是 Matery主题, 并使用Hexo博客框架搭建的.

**Comment by voidoath** [comment]
大佬，我也是使用的hexo+matery主题，但没有您优化的好看。可以简单说下你是怎么把友链页面 每个人的友链设置成一样一样大小的吗

**Comment by liuzhihangs** [comment]
> @voidoath
> 大佬，我也是使用的hexo+matery主题，但没有您优化的好看。可以简单说下你是怎么把友链页面 每个人的友链设置成一样一样大小的吗

这块是很久之前改的了, 确实记不太清了. 但是这块你可以F12 本地调一下. 我这个是放到了一个 card标签里面. 然后设置了属性.
比较忙, 没有看到. 最近也没有写blog. 属性就是把那个瀑布的改成绝对的值. 首页也是一样的改法. 因为我是后端 这个也不太懂. 这块你看下


1. matery.css
2. 1975行左右 .block-with-text属性
3. max-height 成height   

/*max-height: 4.5em;*/
    /* 改成高度固定 4.5 即3行 */
    height: 4.5em;
