### ISSUE TITLE
Hexo中插入Bilibili视频 | liuzhihang

### ISSUE THREAD

**Issue by liuzhihangs** [liuzhihangs/liuzhihang.github.io#135]
https://liuzhihang.com/2019/09/14/hexo-inserts-bilibili-video.html 

 
修改matery主题首页显示视频为Bilibili视频
在Markdown插入Bilibili视频, 并设置大小.

首先找到分享嵌入代码
&lt;iframe src="//player.bilibili.com/player.html

**Comment by voidoath** [comment]
感谢教程
